### ISSUE TITLE
Runtime linking problem in iOS

### ISSUE THREAD

**Issue by XDarinor** [davidbritch/behaviors#1]
Reference to the PCL published over NuGET repostory is not working on iOS. The app gives me the following error at runtime:

System.IO.FileNotFoundException: Could not load file or assembly 'Behaviors' or one of its dependencies

The Windows Universal and Android apps works well.

**Comment by davidbritch** [comment]
I'll investigate this. It's certainly something I've seen in the past, but the problem has always vanished (I've ran the iOS sample many times) before I've tracked it down. As you've said, it's some kind of linking problem.

**Comment by kibiz0r** [comment]
We're seeing this too. We tried using `--linkskip=Behaviors`, but that didn't help.

**Comment by XDarinor** [comment]
I've solved with the simply workaround to clone the git repository and add the project to my visual studio solution. But of course is not the right answer to the problem.

**Comment by davidbritch** [comment]
The issue is that on iOS the Behaviors library is stripped out of the deployed package, because it's not referenced from that project. Changing the linking settings in the iOS project won't help.

A temporary solution is to also add the Behaviors NuGet package to the iOS project, and then reference one of the types from the NuGet package in one of the code-behind files for a XAML file (or in AppDelegate.cs) e.g.

```
var x = typeof(Behaviors.EventHandlerBehavior);
```

This will ensure that the NuGet package is included in the deployed iOS package.

**Comment by Anil86** [comment]
^ above fix solved the problem.

**Comment by gsgou** [comment]
In many other plugins and xamarin libs as a good practice is a static Init() defined for this reason:
https://github.com/jamesmontemagno/ImageCirclePlugin/blob/dc217d99e06a43583f26d277e5614d9ac5e7cfce/src/ImageCircle.Forms.Plugin.iOSUnified/ImageCircleRenderer.cs

**Comment by davidbritch** [comment]
I've republished the package with all the types marked with the `[Preserve]` attribute. This should stop the linker removing the types that aren't statically referenced by the calling application.

**Comment by CarLoOSX** [comment]
Having this isue after updating to Netstandard project. I tried in App Delegate  : 
			var x = typeof(Behaviors.EventHandlerBehavior);
before LoadApplication(new App()); but still with this issue. I'm using .Net Standard 2.0 and Xamarin.forms 3.0.0.482510

Any Idea ?? Before updating to netstandar it was running OK.

Thank you

**Comment by CarLoOSX** [comment]
working with your workarround: 
                        <behaviors:ActionCollection>
sorry seems to appear System.Reflection.TargetInvocationException in VS mac only.

**Comment by davidbritch** [comment]
I'll be pushing out a new release at the end of the week that fixes it.
