### ISSUE TITLE
InvokeCommandAction not found in xmlns clr-namespace:Behaviors;assembly=Behaviors'

### ISSUE THREAD

**Issue by georgikoemdzhiev** [davidbritch/behaviors#10]
Hello! I recently came accros this awesome library and wanted to give it a try. However, when I try to use **DataChangedBehavior** and **InvokeCommandAction** I am getting the above-mentioned error. I have copied the use of the library from your sample code in the repo:

```
<StackLayout>
	<Label Text="Invoke Command when Data Changes" FontAttributes="Bold" HorizontalOptions="Center" />
	<Entry x:Name="entry" Placeholder="Enter Xamarin here">
		<Entry.Behaviors>
			<behaviors:DataChangedBehavior Binding="{Binding Path=Text, Source={x:Reference entry}}"
										   ComparisonCondition="Equal" Value="Xamarin">
				<behaviors:InvokeCommandAction Command="{Binding OutputMessageCommand}"
											   CommandParameter="{Binding Path=Text, Source={x:Reference entry}}" />
			</behaviors:DataChangedBehavior>
		</Entry.Behaviors>
	</Entry>
	<Label Text="{Binding MessageText}" />
</StackLayout>
```

**Comment by georgikoemdzhiev** [comment]
I managed to get the library working by installing it into my UWP project as well as my shared library project.  :)

**Comment by jpmock** [comment]
I had this issue and got it working by compiling the Xaml.

I have to place this above namespace declaration in my App.xaml.cs:

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
