### ISSUE TITLE
Net standard

### ISSUE THREAD

**Issue by acaliaro** [davidbritch/behaviors#11]
Hi @davidbritch . Is this package compatible with NS2.0?

**Comment by davidbritch** [comment]
@acaliaro No. It needs updating. I'll add it to my list.

**Comment by davidbritch** [comment]
@acaliaro I've updated the code in the net-standard branch. Next week I'll re-publish the NuGet package.

**Comment by acaliaro** [comment]
Thanks @davidbritch it's a great!

**Comment by davidbritch** [comment]
Done.

**Comment by acaliaro** [comment]
Excellent. Thanks @davidbritch
