### ISSUE TITLE
Have view listen to event on VM

### ISSUE THREAD

**Issue by weitzhandler** [davidbritch/behaviors#12]
Hello @davidbritch and thanks for this wonderful repo!

In my scenario I have a ViewModel that wants to signal the View to do a one-time action (animation etc.).

Does this library offer anything that can achieve that?

**Comment by davidbritch** [comment]
Afraid not. That sounds like something you could achieve with `MessagingCenter`?

**Comment by weitzhandler** [comment]
Thanks for your response!
