### ISSUE TITLE
ItemTapped event

### ISSUE THREAD

**Issue by acaliaro** [davidbritch/behaviors#16]
Hi @davidbritch 

I have this code

            InvokeCommandAction icsSelectedItem = new InvokeCommandAction();
            icsSelectedItem.SetBinding(InvokeCommandAction.CommandProperty, "ItemSelectedCommand");
            EventHandlerBehavior ehbSelectedItem = new EventHandlerBehavior() { EventName = "ItemSelected" };
            ehbSelectedItem.Actions.Add(icsSelectedItem);

It works fine.

But I would like to use ItemTapped event, not ItemSelected. If I change EventName to ItemTapped, It does not work...

**Comment by davidbritch** [comment]
What control is the `EventHandlerBehavior` added to?

**Comment by acaliaro** [comment]
A listview

**Comment by davidbritch** [comment]
What version of the NuGet are you using? I just tried it in XAML and had no problems. I'll try C# next.

**Comment by davidbritch** [comment]
I just did the following, and it worked just fine:

```
InvokeCommandAction icsSelectedItem = new InvokeCommandAction();
icsSelectedItem.SetBinding(InvokeCommandAction.CommandProperty, "OutputMessageCommand");
EventHandlerBehavior ehbSelectedItem = new EventHandlerBehavior { EventName = "ItemTapped" };
ehbSelectedItem.Actions.Add(icsSelectedItem);
listView.Behaviors.Add(ehbSelectedItem);
```

It worked perfectly for both `ItemSelected` and `ItemTapped`. This was against the latest Behaviors library source code (v1.4.0 of the NuGet).

**Comment by acaliaro** [comment]
1.3.0

**Comment by acaliaro** [comment]
to use 1.4 do I have to upgrade XF to 3.0?

**Comment by davidbritch** [comment]
Afraid so.

**Comment by davidbritch** [comment]
I'm going to close this issue. Afraid that, because of the `GoToStateAction` class, this library is now dependent upon Xamarin.Forms 3.0. The only way to avoid this is to use the source directly, and delete the `GoToStateAction` class.
