### ISSUE TITLE
Currently selected item in ListView not properly passed to Command method

### ISSUE THREAD

**Issue by Anil86** [davidbritch/behaviors#2]
Bug: Using ListView's `ItemSelected` event with `InvokeCommandAction` & passing selected item using `CommandParameter` passes previously selected item (instead of currently selected item).

Note: Passing selected item using `Converter` works fine.

**Comment by aizefler** [comment]
@Anil86 , unfortunately, it did not work "Convert" in my scenario using MVVM framework Prism, to run the Android application error occurs at startup displaying the message "System.NullReferenceException:. Object reference not set to an instance of an object."

When references to "Convert" are removed from the xaml file works fine, but returns the SelectedItemChangedEventArgs object, I would like to return to a specific object.

Will is missing some implementation detail not included in the documentation?

**Comment by Anil86** [comment]
@izefler I've changed my strategy 

from 
passing Selected item via Command 

to 
directly binding selected item (using ListView's SelectedItem property) to a Model property in ViewModel. 

So my command no longer needs Selected item to be passed. I directly use ViewModel property in Command's method.

**Comment by Anil86** [comment]
Using Converter property instead of CommandParameter solves the problem.

With converter you can convert ListView's EventArgs to selected item.
