### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by MaxenceMax** [davidbritch/behaviors#5]
i got this error on iOS platform only, does iOS need to something special to work ? It seems like the method "EventToCommandBehavior" can not be found in namespace. It's working on android platform.

**Comment by davidbritch** [comment]
Sounds like a linking problem. See https://github.com/davidbritch/behaviors/issues/1

**Comment by davidbritch** [comment]
Is this still an issue for you?

**Comment by davidbritch** [comment]
Closed due to no response.
