### ISSUE TITLE
Behaviors in GestureRecognizers

### ISSUE THREAD

**Issue by andresgutice** [davidbritch/behaviors#7]
Hi there, i have this code:
`<Image Source="{Binding FavoriteIcon,Mode=TwoWay}">
                                        <Image.GestureRecognizers>
                                            <TapGestureRecognizer Command="{Binding CommmandSetFavorite}"/>
                                        </Image.GestureRecognizers>
                                    </Image>`

I would like that when touch it this'll make an animation of ScaleAction through GestureRecognizers, how could i do it?

**Comment by davidbritch** [comment]
Apologies for the delay in responding to this.

I can't see a way of doing this with the Behaviors library. While the `Image` view has a `Behaviors` property that a behavior can be attached to, it doesn't have a suitable event that can be listened to, to detect a tap.

Similarly, a `TapGestureRecognizer` doesn't have a `Behaviors` property that a behavior can be attached to.

Hence, I can't see a way of executing a `ScaleAction` in response to a `TapGestureRecognizer` with the library as it is. Apologies!
